apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/hello/healthz/live
spec:
  type: NodePort
  selector:
    app: backend-deployment
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
